### ISSUE TITLE
System.DllNotFoundException

### ISSUE THREAD

**Issue by volkan-a** [pmahend1/Xamarin#1]
Just run as it is but I got this error:

System.DllNotFoundException: libCppLib.so assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) XamarinNDKSample.XamCppLibCS.Add(int,int)
  at XamarinNDKSample.MainPage.ButtonGetResult_Clicked (System.Object sender, System.EventArgs e) [0x0003b] in /Users/volkanakkaya/RiderProjects/Xamarin/XamarinNDKSample/XamarinNDKSample/XamarinNDKSample/MainPage.xaml.cs:28

**Comment by Rytisgit** [comment]
Hey, I had the same problem too, what's needed to do is sort of described in the https://github.com/pmahend1/Xamarin/tree/master/XamarinNDKSample/XamarinNDKSample/XamarinNDKSample.Android/lib readme.

you need to add the abi that your emulator uses in the project lib folder:

![image](https://user-images.githubusercontent.com/36188103/81845947-01eb1400-955a-11ea-8c9d-9fb7dac87c5f.png)
![image](https://user-images.githubusercontent.com/36188103/81845969-09aab880-955a-11ea-851e-78cb1ebd0575.png)

Then you need to build the c++ project to match the abi you added:
![image](https://user-images.githubusercontent.com/36188103/81846061-2e069500-955a-11ea-971c-92aadc7fa508.png)
because the default is configured to only run the arm64 abi build

After doing this the error of not finding the dll is gone and the calculator works
![image](https://user-images.githubusercontent.com/36188103/81846253-73c35d80-955a-11ea-8aa4-d7ea7358e709.png)

**Comment by pmahend1** [comment]
@volkan-a Do you still have the issue?

**Comment by volkan-a** [comment]
Yes, that didn’t work for me.

Volkan.

**Comment by pmahend1** [comment]
@volkan-a I had not added files for all ABIs , did you follow @Rytisgit 's suggestion? If not check with latest master, you should not face issues now.
